- name: Install MariaDB
  yum:
    name: mariadb-server
    state: installed
    update_cache: True
- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
- name: Create app DB
  mysql_db:
    name: "{{ db_name }}"
    state: present
- name: Create DB user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_pass }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
